stages:
  - test
  - format

default:
  image: gradle:8-jdk21
  before_script:
    - apt-get update && apt-get install -y maven

# -------------------------
# Test & Analyze Job
# -------------------------
test-and-analyze:
  stage: test
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - chmod +x gradlew
    - chmod +x .shell/publish_gen_to_maven_local.sh
    - ./gradlew test jacocoTestReport
    - ./gradlew sonar --info -Dsonar.projectKey=${SONAR_PROJECT_KEY} -Dsonar.organization=${SONAR_ORGANIZATION} -Dsonar.host.url=${SONAR_HOST_URL} -Dsonar.token=${SONAR_TOKEN} -Dsonar.qualitygate.wait=true

  timeout: 30 minutes
  artifacts:
    when: always
    paths:
      - build/reports/jacoco/
      - build/test-results/
      - build/classes/
    expire_in: 1 hour
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_COMMIT_REF_NAME == 'main' || $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_PIPELINE_SOURCE == "web"

format:
  stage: format
  script:
    - chmod +x format.sh
    - ./format.sh
    - git diff --exit-code
  timeout: 20 minutes
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "web"